-- Console activity: no window, no graphics.
-- Do not edit this file.

io.stdout:setvbuf("no")

function love.conf(t)
    t.modules.window   = false
    t.modules.graphics = false
    t.modules.audio    = false
end

-- main.lua is plain Lua: it runs top to bottom, then the program ends here.
function love.update()
    love.event.quit()
end

function love.errorhandler(msg)
    io.write("\nError: ", tostring(msg), "\n")
    local shown = false
    for line in debug.traceback("", 2):gmatch("[^\n]+") do
        if line:match("%.lua:%d+") and not line:match('%[love "') and not line:match("^%s*%[C%]") then
            if not shown then io.write("\n"); shown = true end
            io.write("  ", (line:gsub("^%s+", "")), "\n")
        end
    end
    io.write("\n")
end
