-- Graphics activity: opens a window.
-- Do not edit this file.

io.stdout:setvbuf("no")

function love.conf(t)
    t.window.title  = "Activity"
    t.window.width  = 800
    t.window.height = 600

    t.modules.joystick = false
    t.modules.physics  = false
end